def getFortunes():
    return [
        "Your future is created by what you do today, not tomorrow.",
    "The best way to predict the future is to create it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "You will meet someone special who will change your life.",
    "The journey of a thousand miles begins with one step.",
    "Your talents will be recognized and suitably rewarded.",
    "You will find joy in unexpected places.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are on the right path; keep moving forward.",
    "Your life is about to become very exciting.",
    "A beautiful, smart, and loving person will come into your life.",
    "Your hard work will soon pay off.",
    "A fresh start will put you on your way.",
    "Good news will come to you from far away.",
    "Your future is bright.",
    "You will soon take a vacation.",
    "You will be recognized for your contributions.",
    "You will achieve great success.",
    "A thrilling time is in your immediate future.",
    "Your ability to juggle many tasks will take you far.",
    "Expect great things from your future.",
    "You will be surrounded by good friends.",
    "You will soon be in the company of powerful people.",
    "A new adventure is on the horizon.",
    "Your ideas will lead to great success.",
    "You will find peace and happiness.",
    "Someone is thinking of you.",
    "A new chapter in your life is about to begin.",
    "You will receive an unexpected gift.",
    "You will make a difference in someone's life.",
    "Opportunities will come knocking at your door.",
    "You will soon be rewarded for your efforts.",
    "Your dreams are within reach.",
    "You will find love where you least expect it.",
    "A happy event will take place soon.",
    "Someone close to you will give you valuable advice.",
    "You will discover a hidden talent.",
    "You will be asked to take on a leadership role.",
    "The winds of change are blowing in your favor.",
    "You will inspire someone with your actions.",
    "An old friend will re-enter your life.",
    "A small act of kindness will lead to great rewards.",
    "Your positive attitude will attract positive outcomes.",
    "The universe is conspiring in your favor.",
    "A financial opportunity will come your way.",
    "Your health will improve.",
    "Your skills will be in high demand.",
    "You will receive praise for your work.",
    "You will find the strength to overcome obstacles.",
    "You are destined for greatness.",
    "Good fortune is on its way to you.",
    "Your efforts will be appreciated.",
    "A new friendship will blossom.",
    "A moment of spontaneity will lead to joy.",
    "You will achieve something you never thought possible.",
    "Your creativity will shine brightly.",
    "A pleasant surprise is in store for you.",
    "You will be blessed with good fortune.",
    "You will have a chance to start anew.",
    "Your unique talents will be recognized.",
    "You will find solutions to problems that seem insurmountable.",
    "Your determination will pay off.",
    "You will discover a new passion.",
    "You will soon experience personal growth.",
    "Your intuition will guide you well.",
    "You will have a reason to celebrate soon.",
    "Your hard work will lead to prosperity.",
    "You will bring joy to others.",
    "A new opportunity for travel is on the horizon.",
    "Your insight will be valued by those around you.",
    "You will experience a burst of creativity.",
    "A new job or project will come your way.",
    "Your resilience will impress those around you.",
    "You will learn valuable lessons from your experiences.",
    "You will create lasting memories.",
    "Your positive outlook will attract good things.",
    "You will discover new interests and hobbies.",
    "You will be supported by those you least expect.",
    "A chance encounter will lead to a new opportunity.",
    "You will find joy in simple pleasures.",
    "Your confidence will grow.",
    "You will be a source of inspiration for others.",
    "You will find clarity in a confusing situation.",
    "Your generosity will come back to you tenfold.",
    "A new love may be around the corner.",
    "You will receive good news about your health.",
    "A cherished dream will soon come true.",
    "Your persistence will lead to achievement.",
    "You will find strength in difficult times.",
    "An unexpected visitor will bring joy.",
    "You will be rewarded for your loyalty.",
    "You will have a breakthrough in your work.",
    "Your kindness will be remembered.",
    "A long-awaited wish will come true.",
    "You will make a positive impact in your community.",
    "Your unique perspective will be appreciated.",
    "You will embark on a new journey.",
    "You will create something beautiful.",
    "A fresh perspective will help you solve a problem.",
    "You will soon have a reason to smile.",
    "Your passion will lead you to success.",
    "You will find happiness in unexpected places.",
    "You will be surrounded by positivity.",
    "You will soon gain new insights.",
    "A mentor will guide you in your endeavors.",
    "You will discover new ways to express yourself.",
    "Your heart will lead you in the right direction.",
    "A new relationship will flourish.",
    "Your efforts will bear fruit.",
    "You will soon receive an offer you can't refuse.",
    "You will find beauty in everyday moments.",
    "You will discover a new level of understanding.",
    "A project will be completed successfully.",
    "Your dreams will inspire others.",
    "You will be presented with a unique opportunity.",
    "Your generosity will bring you unexpected rewards.",
    "You will be recognized for your hard work.",
    "A chance to shine is coming your way.",
    "Your wisdom will guide you through challenges.",
    "You will find a solution to a lingering problem.",
    "A long-held desire will come to fruition.",
    "You will soon feel a sense of accomplishment.",
    "Your intuition will lead you to make the right choices.",
    "A new perspective will open doors for you.",
    "You will experience personal and professional growth.",
    "You will find joy in the little things.",
    "A good friend will offer you support.",
    "You will soon hear news that makes you happy.",
    "You will find the motivation you need.",
    "You will be pleasantly surprised by someone's kindness.",
    "A significant decision will lead to positive change.",
    "You will learn to embrace change.",
    "Your creative ideas will flourish.",
    "You will be rewarded for your patience.",
    "Your talents will shine in the right environment.",
    "You will soon meet someone who inspires you.",
    "A new opportunity for collaboration is on the horizon.",
    "You will feel a sense of belonging.",
    "You will overcome a challenge you once thought impossible.",
    "You will soon enjoy a well-deserved break.",
    "You will gain recognition for your unique skills.",
    "A new path will reveal itself.",
    "Your laughter will lighten the hearts of others.",
    "You will experience a period of harmony.",
    "Your hard work will not go unnoticed.",
    "You will soon find clarity in a complex situation.",
    "A chance to learn something new is coming.",
    "You will discover the strength within you.",
    "You will bring light to someone's darkness.",
    "A new door will open for you.",
    "You will soon reap the benefits of your labor.",
    "Your presence will uplift those around you.",
    "You will find beauty in every moment.",
    "A surprise visit will bring joy.",
    "Your enthusiasm will inspire those around you.",
    "A new friendship will blossom.",
    "You will soon be in the spotlight.",
    "Your courage will be rewarded.",
    "You will soon find a reason to celebrate.",
    "You will discover a new passion or interest.",
    "Your hard work will yield amazing results.",
    "You will find new opportunities for growth.",
    "Your kindness will make a difference.",
    "You will receive support from unexpected sources.",
    "A new chapter in your life will begin.",
    "You will soon be recognized for your contributions.",
    "Your creativity will open new doors.",
    "You will find a new direction in your life.",
    "Your efforts will lead to new opportunities.",
    "You will soon have a breakthrough.",
    "You will be able to achieve your goals.",
    "A spark of inspiration will guide you.",
    "Your intuition will lead you to success.",
    "You will discover new ways to express yourself.",
    "Your positive energy will attract good things.",
    "You will find strength in difficult situations.",
    "A new friend will bring you joy.",
    "You will be pleasantly surprised by someone's generosity.",
    "You will soon have an opportunity to shine.",
    "Your unique gifts will be appreciated.",
    "A new opportunity for travel will arise.",
    "Your laughter will bring joy to others.",
    "You will achieve a long-held dream."
    ]